// Generated by sdkgen go-cli target.
package main

import (
	"fmt"
	"strings"

	eng "github.com/boru-lang/boru/eng/go"
	sdk "github.com/voxgig-sdk/luma-sdk/go"
)

// registerSDKWords installs three native boru words bound to the SDK:
// list / load / update. Each is declared with two overloads matching
// the signature  [query?:(Node or Scalar) entity:atom]:
//
//   [entity:Atom]            — no query (e.g. `list book`)
//   [query:Any entity:Atom]  — query is any Node or Scalar (e.g.
//                              `load {id:1} book`, `load 1 book`)
//
// The entity slot is /q-quoted so a bareword `book` parses as the
// Atom "book" rather than dispatching as an undefined word. Both
// overloads are all-forward (BarrierAllForward), so args are collected
// from the tokens following the word.
func registerSDKWords(r *eng.Registry, client *sdk.LumaSDK) {
	for _, op := range []string{"list", "load", "update"} {
		op := op
		single := eng.Signature{
			Args:      []*eng.Type{eng.TAtom},
			QuoteArgs: map[int]bool{0: true},
			Impl: eng.Go(func(args []eng.Value, _ map[string]eng.Value, _ []eng.Value, _ *eng.Registry) ([]eng.Value, error) {
				return runOp(client, op, nil, args[0])
			}),
			Returns:    []*eng.Type{eng.TAny},
			BarrierPos: eng.BarrierAllForward,
		}
		dual := eng.Signature{
			Args:      []*eng.Type{eng.TAny, eng.TAtom},
			QuoteArgs: map[int]bool{1: true},
			Impl: eng.Go(func(args []eng.Value, _ map[string]eng.Value, _ []eng.Value, _ *eng.Registry) ([]eng.Value, error) {
				q := args[0]
				return runOp(client, op, &q, args[1])
			}),
			Returns:    []*eng.Type{eng.TAny},
			BarrierPos: eng.BarrierAllForward,
		}
		r.RegisterNativeFunc(eng.NativeFunc{
			Name:       op,
			Signatures: []eng.Signature{single, dual},
		})
	}
}

func runOp(client *sdk.LumaSDK, op string, query *eng.Value, entityAtom eng.Value) ([]eng.Value, error) {
	entityName, err := eng.AsAtom(entityAtom)
	if err != nil {
		return nil, fmt.Errorf("%s: entity argument is not an atom: %w", op, err)
	}
	ent, err := entityFor(client, entityName)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", op, err)
	}

	var arg map[string]any
	if query != nil {
		arg, err = queryToMap(*query)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", op, err)
		}
	}

	var result any
	switch op {
	case "list":
		result, err = ent.List(arg, nil)
	case "load":
		result, err = ent.Load(arg, nil)
	case "update":
		result, err = ent.Update(arg, nil)
	default:
		return nil, fmt.Errorf("unknown op %q", op)
	}
	if err != nil {
		return nil, err
	}
	return []eng.Value{eng.FromNative(extractData(result))}, nil
}

// entityFor dispatches on the lowercase entity name. The generator
// emits one `case "<name>":` per entity defined in the SDK model.
func entityFor(client *sdk.LumaSDK, name string) (sdk.LumaEntity, error) {
	switch strings.ToLower(name) {
	case "calendar":
		return client.Calendar(nil), nil
	case "calendar_admin":
		return client.CalendarAdmin(nil), nil
	case "calendar_coupon":
		return client.CalendarCoupon(nil), nil
	case "calendar_event":
		return client.CalendarEvent(nil), nil
	case "calendar_event_approval":
		return client.CalendarEventApproval(nil), nil
	case "calendar_event_rejection":
		return client.CalendarEventRejection(nil), nil
	case "contact":
		return client.Contact(nil), nil
	case "contact_block":
		return client.ContactBlock(nil), nil
	case "contact_restore":
		return client.ContactRestore(nil), nil
	case "contact_tag":
		return client.ContactTag(nil), nil
	case "contact_tag_assignment":
		return client.ContactTagAssignment(nil), nil
	case "entity_lookup":
		return client.EntityLookup(nil), nil
	case "event":
		return client.Event(nil), nil
	case "event_cancel_request":
		return client.EventCancelRequest(nil), nil
	case "event_coupon":
		return client.EventCoupon(nil), nil
	case "event_tag":
		return client.EventTag(nil), nil
	case "event_tag_assignment":
		return client.EventTagAssignment(nil), nil
	case "guest":
		return client.Guest(nil), nil
	case "guest_invite":
		return client.GuestInvite(nil), nil
	case "guest_ticket":
		return client.GuestTicket(nil), nil
	case "host":
		return client.Host(nil), nil
	case "image_upload":
		return client.ImageUpload(nil), nil
	case "member":
		return client.Member(nil), nil
	case "membership_tier":
		return client.MembershipTier(nil), nil
	case "organization_admin":
		return client.OrganizationAdmin(nil), nil
	case "organization_calendar":
		return client.OrganizationCalendar(nil), nil
	case "organization_event":
		return client.OrganizationEvent(nil), nil
	case "organization_event_transfer":
		return client.OrganizationEventTransfer(nil), nil
	case "ticket_type":
		return client.TicketType(nil), nil
	case "user":
		return client.User(nil), nil
	case "webhook":
		return client.Webhook(nil), nil

	}
	return nil, fmt.Errorf("unknown entity %q", name)
}

// queryToMap converts a boru Value (Map or Scalar) into the
// `map[string]any` shape the SDK expects. Maps are unwrapped via
// eng.ToNative. Scalars are wrapped as {"id": <value>} so the
// shorthand `load 1 book` becomes `load {id:1} book`.
func queryToMap(v eng.Value) (map[string]any, error) {
	if v.Parent.ConformsTo(eng.TMap) {
		m, ok := eng.ToNative(v).(map[string]any)
		if !ok {
			return nil, fmt.Errorf("query map could not be unwrapped")
		}
		return m, nil
	}
	if v.Parent.ConformsTo(eng.TScalar) {
		return map[string]any{"id": eng.ToNative(v)}, nil
	}
	return nil, fmt.Errorf("query must be a Map or Scalar, got %s", v.Parent)
}

// extractData walks an SDK result and replaces any sdk.Entity wrapper
// with the underlying record via .Data().
func extractData(x any) any {
	switch v := x.(type) {
	case sdk.Entity:
		return extractData(v.Data())
	case []any:
		out := make([]any, len(v))
		for i, e := range v {
			out[i] = extractData(e)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(v))
		for k, vv := range v {
			out[k] = extractData(vv)
		}
		return out
	}
	return x
}
