// Generated by sdkgen go-mcp target.
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/modelcontextprotocol/go-sdk/mcp"
	sdk "github.com/voxgig-sdk/luma-sdk/go"
)

// Args is the common argument shape for both tools. `entity` selects
// the SDK entity to operate on; `query` is the optional reqmatch /
// reqdata map passed through to the SDK. For load, `query` should be
// `{"id": <value>}`. For list, omit `query` or pass an empty map.
type Args struct {
	Entity string         `json:"entity" jsonschema:"calendar | calendar_admin | calendar_coupon | calendar_event | calendar_event_approval | calendar_event_rejection | contact | contact_block | contact_restore | contact_tag | contact_tag_assignment | entity_lookup | event | event_cancel_request | event_coupon | event_tag | event_tag_assignment | guest | guest_invite | guest_ticket | host | image_upload | member | membership_tier | organization_admin | organization_calendar | organization_event | organization_event_transfer | ticket_type | user | webhook"`
	Query  map[string]any `json:"query,omitempty" jsonschema:"optional match map e.g. {\"id\":1} for load, omit for list"`
}

func registerTools(server *mcp.Server, client *sdk.LumaSDK) {
	mcp.AddTool(server, &mcp.Tool{
		Name: "luma_list",
		Description: "List records from Luma. " +
			"Args: entity (one of the supported SDK entities), query (optional filter map). " +
			"Returns the first page of records as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "list", args)
	})

	mcp.AddTool(server, &mcp.Tool{
		Name: "luma_load",
		Description: "Load a single record from Luma. " +
			"Args: entity, query ({\"id\":N} required). Returns the record as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "load", args)
	})
}

func runOp(client *sdk.LumaSDK, op string, args Args) (*mcp.CallToolResult, any, error) {
	ent, err := entityFor(client, args.Entity)
	if err != nil {
		return toolError(err.Error())
	}

	var result any
	switch op {
	case "list":
		result, err = ent.List(args.Query, nil)
	case "load":
		result, err = ent.Load(args.Query, nil)
	default:
		return toolError(fmt.Sprintf("unknown op %q", op))
	}
	if err != nil {
		return toolError(err.Error())
	}

	// SDK returns *Entity wrappers; unwrap each via .Data() to get a
	// plain map[string]any (or []any of maps for list) suitable for
	// JSON marshalling.
	data := extractData(result)
	body, err := json.MarshalIndent(data, "", "  ")
	if err != nil {
		return toolError(fmt.Sprintf("marshal: %v", err))
	}
	return &mcp.CallToolResult{
		Content: []mcp.Content{
			&mcp.TextContent{Text: string(body)},
		},
	}, data, nil
}

// entityFor dispatches on the lowercase entity name. The generator
// emits one `case "<name>":` per entity defined in the SDK model.
func entityFor(client *sdk.LumaSDK, name string) (sdk.LumaEntity, error) {
	switch strings.ToLower(name) {
	case "calendar":
		return client.Calendar(nil), nil
	case "calendar_admin":
		return client.CalendarAdmin(nil), nil
	case "calendar_coupon":
		return client.CalendarCoupon(nil), nil
	case "calendar_event":
		return client.CalendarEvent(nil), nil
	case "calendar_event_approval":
		return client.CalendarEventApproval(nil), nil
	case "calendar_event_rejection":
		return client.CalendarEventRejection(nil), nil
	case "contact":
		return client.Contact(nil), nil
	case "contact_block":
		return client.ContactBlock(nil), nil
	case "contact_restore":
		return client.ContactRestore(nil), nil
	case "contact_tag":
		return client.ContactTag(nil), nil
	case "contact_tag_assignment":
		return client.ContactTagAssignment(nil), nil
	case "entity_lookup":
		return client.EntityLookup(nil), nil
	case "event":
		return client.Event(nil), nil
	case "event_cancel_request":
		return client.EventCancelRequest(nil), nil
	case "event_coupon":
		return client.EventCoupon(nil), nil
	case "event_tag":
		return client.EventTag(nil), nil
	case "event_tag_assignment":
		return client.EventTagAssignment(nil), nil
	case "guest":
		return client.Guest(nil), nil
	case "guest_invite":
		return client.GuestInvite(nil), nil
	case "guest_ticket":
		return client.GuestTicket(nil), nil
	case "host":
		return client.Host(nil), nil
	case "image_upload":
		return client.ImageUpload(nil), nil
	case "member":
		return client.Member(nil), nil
	case "membership_tier":
		return client.MembershipTier(nil), nil
	case "organization_admin":
		return client.OrganizationAdmin(nil), nil
	case "organization_calendar":
		return client.OrganizationCalendar(nil), nil
	case "organization_event":
		return client.OrganizationEvent(nil), nil
	case "organization_event_transfer":
		return client.OrganizationEventTransfer(nil), nil
	case "ticket_type":
		return client.TicketType(nil), nil
	case "user":
		return client.User(nil), nil
	case "webhook":
		return client.Webhook(nil), nil

	}
	return nil, fmt.Errorf("unknown entity %q", name)
}

// extractData walks an SDK result and replaces any sdk.Entity wrapper
// with its underlying record (via .Data()).
func extractData(x any) any {
	switch v := x.(type) {
	case sdk.Entity:
		return extractData(v.Data())
	case []any:
		out := make([]any, len(v))
		for i, e := range v {
			out[i] = extractData(e)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(v))
		for k, vv := range v {
			out[k] = extractData(vv)
		}
		return out
	}
	return x
}

func toolError(msg string) (*mcp.CallToolResult, any, error) {
	return &mcp.CallToolResult{
		IsError: true,
		Content: []mcp.Content{
			&mcp.TextContent{Text: msg},
		},
	}, nil, nil
}
